In [6]:
import pandas as pd
import os

In [7]:
print(os.getcwd())

/Users/shreyanshpathak/Desktop/Python Projects/ai-calorie-calculator/analytics

In [8]:
df = pd.read_csv('../data/raw/Indian_Food_Nutrition_Processed.csv')

In [9]:
df.head()

,Dish Name,Calories (kcal),Carbohydrates (g),Protein (g),Fats (g),Free Sugar (g),Fibre (g),Sodium (mg),Calcium (mg),Iron (mg),Vitamin C (mg),Folate (µg)
0,Hot tea (Garam Chai),16.14,2.58,0.39,0.53,2.58,0.00,3.12,14.20,0.02,0.50,1.80
1,Instant coffee,23.16,3.65,0.64,0.75,3.62,0.00,4.92,20.87,0.06,1.51,5.60
2,Espreso coffee,51.54,6.62,1.75,2.14,6.53,0.00,13.98,58.10,0.15,1.51,5.53
3,Iced tea,10.34,2.70,0.03,0.01,2.70,0.00,0.23,1.18,0.02,5.95,1.28
4,Raw mango drink (Aam panna),35.92,9.05,0.16,0.03,7.49,0.61,79.82,7.08,0.14,45.30,14.05

In [10]:
df.shape

(1014, 12)

In [11]:
df['Dish Name'].unique()

array(['Hot tea (Garam Chai)', 'Instant coffee', 'Espreso coffee', ...,
       'Tomato chutney (Tamatar ki chutney)', 'Tomato ketchup',
       'Bengal 5 Spice Blend (Panch Phoran)'], shape=(1014,), dtype=object)

In [12]:
df['Dish Name'].isnull().sum()

np.int64(0)

In [13]:
df['Calories (kcal)'].isnull().sum()

np.int64(0)

In [14]:
df['Carbohydrates (g)'].isnull().sum()

np.int64(0)

In [15]:
df['Protein (g)'].isnull().sum()

np.int64(0)

In [16]:
df['Fats (g)'].isnull().sum()

np.int64(0)

In [17]:
df['Free Sugar (g)'].isnull().sum()

np.int64(0)

In [18]:
df['Fibre (g)'].isnull().sum()

np.int64(0)

In [19]:
df['Sodium (mg)'].isnull().sum()

np.int64(0)

In [20]:
df['Calcium (mg)'].isnull().sum()

np.int64(0)

In [21]:
df['Iron (mg)'].isnull().sum()

np.int64(0)

In [22]:
df['Vitamin C (mg)'].isnull().sum()

np.int64(82)

In [23]:
df['Folate (µg)'].isnull().sum()

np.int64(82)

In [24]:
df['Vitamin C (mg)'].isnull().equals(df['Folate (µg)'].isnull())

True

In [25]:
df.duplicated().sum()

np.int64(0)

In [27]:
df['Dish Name'].duplicated().sum()

np.int64(0)

In [29]:
df.dtypes

Dish Name             object
Calories (kcal)      float64
Carbohydrates (g)    float64
Protein (g)          float64
Fats (g)             float64
Free Sugar (g)       float64
Fibre (g)            float64
Sodium (mg)          float64
Calcium (mg)         float64
Iron (mg)            float64
Vitamin C (mg)       float64
Folate (µg)          float64
dtype: object

In [30]:
clean_df = df.copy()

In [31]:
clean_df = clean_df.drop(columns=['Vitamin C (mg)', 'Folate (µg)'])

In [32]:
clean_df.shape

(1014, 10)

In [34]:
clean_df.columns.tolist()

['Dish Name',
 'Calories (kcal)',
 'Carbohydrates (g)',
 'Protein (g)',
 'Fats (g)',
 'Free Sugar (g)',
 'Fibre (g)',
 'Sodium (mg)',
 'Calcium (mg)',
 'Iron (mg)']

In [35]:
numerical_cols = clean_df.select_dtypes(include=['number'])

In [36]:
negative_counts = (numerical_cols < 0).sum()

In [37]:
columns_with_negatives = negative_counts[negative_counts > 0]

In [38]:
columns_with_negatives

Series([], dtype: int64)

In [39]:
clean_df.to_csv('../data/processed/Indian_Food_Nutrition_Processed.csv', index=False)

In [41]:
verify_df = pd.read_csv('../data/processed/Indian_Food_Nutrition_Processed.csv')

In [42]:
verify_df.shape

(1014, 10)

In [44]:
verify_df.isnull().sum()

Dish Name            0
Calories (kcal)      0
Carbohydrates (g)    0
Protein (g)          0
Fats (g)             0
Free Sugar (g)       0
Fibre (g)            0
Sodium (mg)          0
Calcium (mg)         0
Iron (mg)            0
dtype: int64

In [45]:
verify_df.head()

,Dish Name,Calories (kcal),Carbohydrates (g),Protein (g),Fats (g),Free Sugar (g),Fibre (g),Sodium (mg),Calcium (mg),Iron (mg)
0,Hot tea (Garam Chai),16.14,2.58,0.39,0.53,2.58,0.00,3.12,14.20,0.02
1,Instant coffee,23.16,3.65,0.64,0.75,3.62,0.00,4.92,20.87,0.06
2,Espreso coffee,51.54,6.62,1.75,2.14,6.53,0.00,13.98,58.10,0.15
3,Iced tea,10.34,2.70,0.03,0.01,2.70,0.00,0.23,1.18,0.02
4,Raw mango drink (Aam panna),35.92,9.05,0.16,0.03,7.49,0.61,79.82,7.08,0.14

In [46]:
clean_df['Dish Name'].ne(clean_df['Dish Name'].str.strip()).sum()

np.int64(46)

In [47]:
clean_df['Dish Name'] = clean_df['Dish Name'].str.strip()

In [49]:
clean_df['Dish Name'].str.lower().nunique()

1014

In [50]:
clean_df['Dish Name'].nunique()

1014

In [51]:
clean_df[
    clean_df['Dish Name'].str.strip().str.casefold().duplicated(keep=False)
].sort_values('Dish Name')

Empty DataFrame
Columns: [Dish Name, Calories (kcal), Carbohydrates (g), Protein (g), Fats (g), Free Sugar (g), Fibre (g), Sodium (mg), Calcium (mg), Iron (mg)]
Index: []

In [52]:
import sqlite3

In [53]:
csv_path = '../data/processed/Indian_Food_Nutrition_Processed.csv'
db_path = '../data/processed/food_nutrition.db'

In [54]:
clean_df = pd.read_csv(csv_path)

clean_df.head()

,Dish Name,Calories (kcal),Carbohydrates (g),Protein (g),Fats (g),Free Sugar (g),Fibre (g),Sodium (mg),Calcium (mg),Iron (mg)
0,Hot tea (Garam Chai),16.14,2.58,0.39,0.53,2.58,0.00,3.12,14.20,0.02
1,Instant coffee,23.16,3.65,0.64,0.75,3.62,0.00,4.92,20.87,0.06
2,Espreso coffee,51.54,6.62,1.75,2.14,6.53,0.00,13.98,58.10,0.15
3,Iced tea,10.34,2.70,0.03,0.01,2.70,0.00,0.23,1.18,0.02
4,Raw mango drink (Aam panna),35.92,9.05,0.16,0.03,7.49,0.61,79.82,7.08,0.14

In [55]:
conn = sqlite3.connect(db_path)

clean_df.to_sql(
    name='food_nutrition',
    con=conn,
    if_exists='replace',
    index=False
)

print("Database created successfully!")

Database created successfully!

In [56]:
cursor = conn.cursor()

cursor.execute("SELECT COUNT(*) FROM food_nutrition")

print("Total dishes:", cursor.fetchone()[0])

Total dishes: 1014

In [57]:
result = pd.read_sql_query(
    "SELECT * FROM food_nutrition LIMIT 5",
    conn
)

result

,Dish Name,Calories (kcal),Carbohydrates (g),Protein (g),Fats (g),Free Sugar (g),Fibre (g),Sodium (mg),Calcium (mg),Iron (mg)
0,Hot tea (Garam Chai),16.14,2.58,0.39,0.53,2.58,0.00,3.12,14.20,0.02
1,Instant coffee,23.16,3.65,0.64,0.75,3.62,0.00,4.92,20.87,0.06
2,Espreso coffee,51.54,6.62,1.75,2.14,6.53,0.00,13.98,58.10,0.15
3,Iced tea,10.34,2.70,0.03,0.01,2.70,0.00,0.23,1.18,0.02
4,Raw mango drink (Aam panna),35.92,9.05,0.16,0.03,7.49,0.61,79.82,7.08,0.14

In [58]:
conn.close()

In [1]:
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent))

from src.nutrition import get_food_nutrition

In [2]:
food = get_food_nutrition("Hot tea (Garam Chai)")

print(food)

{'Dish Name': 'Hot tea (Garam Chai)', 'Calories (kcal)': 16.14, 'Carbohydrates (g)': 2.58, 'Protein (g)': 0.39, 'Fats (g)': 0.53, 'Free Sugar (g)': 2.58, 'Fibre (g)': 0.0, 'Sodium (mg)': 3.12, 'Calcium (mg)': 14.2, 'Iron (mg)': 0.02}

In [8]:
import importlib
import src.nutrition as nutrition

importlib.reload(nutrition)

food = nutrition.get_food_nutrition("Instant coffee")
result = nutrition.calculate_nutrition(food, 150)
print(result)

{'Dish Name': 'Instant coffee', 'Calories (kcal)': 34.74, 'Carbohydrates (g)': 5.47, 'Protein (g)': 0.96, 'Fats (g)': 1.12, 'Free Sugar (g)': 5.43, 'Fibre (g)': 0.0, 'Sodium (mg)': 7.38, 'Calcium (mg)': 31.3, 'Iron (mg)': 0.09}